import type { Concert, Tier } from '../types.js';

/** Canonical catalogue. This backend is now the source of truth for it. */
export const concerts: Concert[] = [
  {
    id: 'nova',
    day: '21',
    genre: 'Techno',
    priceFrom: 3500,
    art: 'linear-gradient(135deg,#80EAFF 0%,#9580FF 45%,#FF005C 100%)',
    ru: {
      artist: 'Нина Кравиц',
      tour: 'GALAXIYA Tour',
      venue: 'Газпром Арена',
      city: 'Санкт-Петербург',
      month: 'ИЮН',
      dateLong: 'Сб · 21 июня 2026',
      time: '20:00',
      lineup: [
        { time: '23:00', name: 'Нина Кравиц' },
        { time: '21:30', name: 'Mujuice' },
        { time: '20:00', name: 'Pixelord' },
      ],
    },
    en: {
      artist: 'Nina Kraviz',
      tour: 'GALAXIYA Tour',
      venue: 'Gazprom Arena',
      city: 'Saint Petersburg',
      month: 'JUN',
      dateLong: 'Sat · Jun 21, 2026',
      time: '8:00 PM',
      lineup: [
        { time: '11:00 PM', name: 'Nina Kraviz' },
        { time: '9:30 PM', name: 'Mujuice' },
        { time: '8:00 PM', name: 'Pixelord' },
      ],
    },
  },
  {
    id: 'void',
    day: '04',
    genre: 'Rave',
    priceFrom: 2900,
    art: 'radial-gradient(120% 120% at 20% 10%,#80EAFF 0%,#1FB8D8 38%,#15151D 82%)',
    ru: {
      artist: 'Little Big',
      tour: 'Hypno Rave',
      venue: 'Лужники',
      city: 'Москва',
      month: 'ИЮЛ',
      dateLong: 'Сб · 4 июля 2026',
      time: '19:00',
      lineup: [
        { time: '22:00', name: 'Little Big' },
        { time: '20:30', name: 'Cream Soda' },
        { time: '19:00', name: 'GONE.Fludd' },
      ],
    },
    en: {
      artist: 'Little Big',
      tour: 'Hypno Rave',
      venue: 'Luzhniki',
      city: 'Moscow',
      month: 'JUL',
      dateLong: 'Sat · Jul 4, 2026',
      time: '7:00 PM',
      lineup: [
        { time: '10:00 PM', name: 'Little Big' },
        { time: '8:30 PM', name: 'Cream Soda' },
        { time: '7:00 PM', name: 'GONE.Fludd' },
      ],
    },
  },
  {
    id: 'bass',
    day: '12',
    genre: 'Techno',
    priceFrom: 2500,
    art: 'linear-gradient(120deg,#FF005C 0%,#9580FF 60%,#15151D 100%)',
    ru: {
      artist: 'IC3PEAK',
      tour: 'До свидания',
      venue: 'A2 Green Concert',
      city: 'Санкт-Петербург',
      month: 'ИЮЛ',
      dateLong: 'Сб · 12 июля 2026',
      time: '20:00',
      lineup: [
        { time: '22:30', name: 'IC3PEAK' },
        { time: '21:00', name: 'Kedr Livanskiy' },
        { time: '19:30', name: 'Buttechno' },
      ],
    },
    en: {
      artist: 'IC3PEAK',
      tour: 'Do Svidaniya',
      venue: 'A2 Green Concert',
      city: 'Saint Petersburg',
      month: 'JUL',
      dateLong: 'Sat · Jul 12, 2026',
      time: '8:00 PM',
      lineup: [
        { time: '10:30 PM', name: 'IC3PEAK' },
        { time: '9:00 PM', name: 'Kedr Livanskiy' },
        { time: '7:30 PM', name: 'Buttechno' },
      ],
    },
  },
  {
    id: 'aurelia',
    day: '19',
    genre: 'Pop',
    priceFrom: 3900,
    art: 'linear-gradient(135deg,#9580FF 0%,#80EAFF 100%)',
    ru: {
      artist: 'Zivert',
      tour: 'VINYL #1',
      venue: 'Стадион «Фишт»',
      city: 'Сочи',
      month: 'ИЮЛ',
      dateLong: 'Сб · 19 июля 2026',
      time: '19:00',
      lineup: [
        { time: '22:00', name: 'Zivert' },
        { time: '20:30', name: 'ХАННА' },
        { time: '19:00', name: 'Мари Краймбрери' },
      ],
    },
    en: {
      artist: 'Zivert',
      tour: 'VINYL #1',
      venue: 'Fisht Stadium',
      city: 'Sochi',
      month: 'JUL',
      dateLong: 'Sat · Jul 19, 2026',
      time: '7:00 PM',
      lineup: [
        { time: '10:00 PM', name: 'Zivert' },
        { time: '8:30 PM', name: 'HANNA' },
        { time: '7:00 PM', name: 'Mari Kraymbreri' },
      ],
    },
  },
  {
    id: 'glitch',
    day: '02',
    genre: 'Electro-Pop',
    priceFrom: 3200,
    art: 'linear-gradient(120deg,#15151D 0%,#1FB8D8 50%,#FF005C 100%)',
    ru: {
      artist: 'Cream Soda',
      tour: 'Никаких больше вечеринок',
      venue: 'ВТБ Арена',
      city: 'Москва',
      month: 'АВГ',
      dateLong: 'Вс · 2 августа 2026',
      time: '20:00',
      lineup: [
        { time: '22:00', name: 'Cream Soda' },
        { time: '20:30', name: 'СБПЧ' },
        { time: '19:30', name: 'Mujuice' },
      ],
    },
    en: {
      artist: 'Cream Soda',
      tour: 'No More Parties',
      venue: 'VTB Arena',
      city: 'Moscow',
      month: 'AUG',
      dateLong: 'Sun · Aug 2, 2026',
      time: '8:00 PM',
      lineup: [
        { time: '10:00 PM', name: 'Cream Soda' },
        { time: '8:30 PM', name: 'SBPCh' },
        { time: '7:30 PM', name: 'Mujuice' },
      ],
    },
  },
  {
    id: 'mid',
    day: '15',
    genre: 'Hip-Hop',
    priceFrom: 4200,
    art: 'radial-gradient(120% 120% at 80% 0%,#FF3D85 0%,#9580FF 46%,#0A0A0F 86%)',
    ru: {
      artist: 'Баста',
      tour: 'Баста 40',
      venue: 'Казань Арена',
      city: 'Казань',
      month: 'АВГ',
      dateLong: 'Сб · 15 августа 2026',
      time: '19:00',
      lineup: [
        { time: '22:00', name: 'Баста' },
        { time: '20:30', name: 'Гуф' },
        { time: '19:00', name: 'AntohaMC' },
      ],
    },
    en: {
      artist: 'Basta',
      tour: 'Basta 40',
      venue: 'Kazan Arena',
      city: 'Kazan',
      month: 'AUG',
      dateLong: 'Sat · Aug 15, 2026',
      time: '7:00 PM',
      lineup: [
        { time: '10:00 PM', name: 'Basta' },
        { time: '8:30 PM', name: 'Guf' },
        { time: '7:00 PM', name: 'AntohaMC' },
      ],
    },
  },
  {
    id: 'seraph',
    day: '23',
    genre: 'Pop',
    priceFrom: 3500,
    art: 'linear-gradient(135deg,#80EAFF 0%,#FFFFFF 28%,#9580FF 68%,#FF005C 100%)',
    ru: {
      artist: 'Егор Крид',
      tour: 'Что было, то прошло',
      venue: 'Екатеринбург Арена',
      city: 'Екатеринбург',
      month: 'АВГ',
      dateLong: 'Вс · 23 августа 2026',
      time: '19:00',
      lineup: [
        { time: '21:30', name: 'Егор Крид' },
        { time: '20:00', name: 'NILETTO' },
        { time: '19:00', name: 'Клава Кока' },
      ],
    },
    en: {
      artist: 'Egor Kreed',
      tour: 'What Was, Has Passed',
      venue: 'Ekaterinburg Arena',
      city: 'Yekaterinburg',
      month: 'AUG',
      dateLong: 'Sun · Aug 23, 2026',
      time: '7:00 PM',
      lineup: [
        { time: '9:30 PM', name: 'Egor Kreed' },
        { time: '8:00 PM', name: 'NILETTO' },
        { time: '7:00 PM', name: 'Klava Koka' },
      ],
    },
  },
  {
    id: 'velvet',
    day: '06',
    genre: 'Hip-Hop',
    priceFrom: 3800,
    art: 'linear-gradient(120deg,#FF005C 0%,#15151D 55%,#80EAFF 125%)',
    ru: {
      artist: 'Скриптонит',
      tour: '911',
      venue: 'Стадион Нижний Новгород',
      city: 'Нижний Новгород',
      month: 'СЕН',
      dateLong: 'Вс · 6 сентября 2026',
      time: '20:00',
      lineup: [
        { time: '22:30', name: 'Скриптонит' },
        { time: '21:00', name: '104' },
        { time: '20:00', name: 'Truwer' },
      ],
    },
    en: {
      artist: 'Scriptonite',
      tour: '911',
      venue: 'Nizhny Novgorod Stadium',
      city: 'Nizhny Novgorod',
      month: 'SEP',
      dateLong: 'Sun · Sep 6, 2026',
      time: '8:00 PM',
      lineup: [
        { time: '10:30 PM', name: 'Scriptonite' },
        { time: '9:00 PM', name: '104' },
        { time: '8:00 PM', name: 'Truwer' },
      ],
    },
  },
];

export const tiers: Tier[] = [
  {
    id: 'ga',
    price: 2900,
    ru: {
      name: 'Танцпол',
      desc: 'Стоя — в сердце толпы',
      perks: ['Доступ в танцевальную зону', 'Официальный браслет фестиваля', 'Тайминг сетов в приложении'],
    },
    en: {
      name: 'General Admission',
      desc: 'Standing — heart of the crowd',
      perks: ['Standing dancefloor access', 'Official festival wristband', 'Set timetable in the app'],
    },
  },
  {
    id: 'gap',
    price: 4500,
    ru: {
      name: 'GA+ Фронт',
      desc: 'Приоритетный фронт у рейлинга',
      perks: ['Быстрый вход без очереди', 'Отдельный бар GA+', 'Экспресс-туалеты'],
    },
    en: {
      name: 'GA+ Front',
      desc: 'Priority pit at the rail',
      perks: ['Fast-track entry, no queue', 'Dedicated GA+ bar', 'Express restrooms'],
    },
  },
  {
    id: 'vip',
    price: 8900,
    ru: {
      name: 'VIP-терраса',
      desc: 'Терраса у сцены',
      perks: ['Терраса у сцены', 'Доступ в VIP-лаундж', 'Приветственный напиток'],
    },
    en: {
      name: 'VIP Deck',
      desc: 'Stage-side terrace',
      perks: ['Stage-side terrace', 'VIP lounge access', 'Welcome drink'],
    },
  },
  {
    id: 'cabana',
    price: 19900,
    ru: {
      name: 'Скайбокс-кабана',
      desc: 'Приватно · до 4 · бутылочный сервис',
      perks: ['Приватная кабана до 4 человек', 'Бутылочный сервис', 'Розыгрыш встречи с артистом'],
    },
    en: {
      name: 'Skybox Cabana',
      desc: 'Private · up to 4 · bottle service',
      perks: ['Private cabana for up to 4', 'Bottle service', 'Artist meet-and-greet raffle'],
    },
  },
];

/** The single mock account the API serves (no real auth in this slice). */
export const MOCK_USER = {
  id: 'u_alisa',
  initials: 'АО',
  email: 'alisa@pulse.live',
  nameRu: 'Алиса Орлова',
  nameEn: 'Alisa Orlova',
  cityRu: 'Москва',
  cityEn: 'Moscow',
  statShows: 27,
  statCities: 9,
  statHours: 142,
};

/** Pre-purchased tickets shown on the account screen. */
export const MOCK_ORDERS = [
  { id: 'PLS-AUR-26', concertId: 'aurelia', tierId: 'vip' as const, qty: 2 },
  { id: 'PLS-SER-26', concertId: 'seraph', tierId: 'gap' as const, qty: 1 },
];
